const _generatedCode = 'Code generated by openapi-generator. DO NOT EDIT.'

const general = (source: string) => `/*
 * ${_generatedCode}
 * source: ${source}
 */
`

const newLineComments = (text = '') =>
    text
        .trim()
        // append a star to all lines
        .replace(/\n/g, '\n * ')
        // removing pending space for previously blank lines
        .replace(/^\n * $/g, '\n *')

const index = (source: string, title: string, description?: string) => `/*
 * ${title}
 * ${newLineComments(description)}
 *
 * NOTE: ${_generatedCode}
 * source: ${source}
 */
`

const property = (description?: string) =>
    description
        ? `/*
 * ${newLineComments(description)}
 */
`
        : ''

export const Comments = { general, index, property }
